---
name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #      - name: Checkout
      #  uses: actions/checkout@v2

      - name: Generate image tag
        id: tag
        run: |
          tag=${GITHUB_SHA::8}
          echo ::set-output name=TAG::${tag}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login in to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginxhello:${{ steps.tag.outputs.TAG }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: image-update
          repository: ${{ github.repository_owner }}/gitops-config-nginxhello
          client-payload: '{"tag": "${{ secrets.DOCKERHUB_USERNAME }}/nginxhello:${{ steps.tag.outputs.TAG }}"}'
